### ISSUE TITLE
增加招募NPC和招募动物功能

### ISSUE THREAD

**Issue by ZevenFang** [alexliyu7352/keshi#8]
你好，这个mod太好玩了，不用再每天麻烦的收集材料，直接虚空获取就可以了。希望可以启用招募NPC和动物的功能，把他们放到牢笼里，然后对话招募。我现在是自己添加的Recruit Anyone，然后把血族亲王抓起来了。
建议血族亲王身上再多加两个蓝图，一个可以生产血族精华，一个可以生产他身上的翅膀背包，可以大幅减少探索地图的时间。

**Comment by alexliyu7352** [comment]
一直都有啊这两个功能， 招募NPC可以直接抓了放到自己基地笼子里面然后对话
也可以制造奴役之戒，然后奴役对方。

任何的动物与机器也可以招募， 同样关在自己基地的笼子里面， 身上有肉或者有工具即可

**Comment by ZevenFang** [comment]
好的，我可能是用了旧版本，我更新下新版本的mod
